runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: ubuntu22

manual_scaling:
  instances: 1
resources:
  cpu: 4
  memory_gb: 6.0
  disk_size_gb: 20

handlers:
  # Serve static files directly from the /static directory
  - url: /static
    static_dir: app/static

  # Serve all other requests via the application
  - url: /.*
    script: auto




