runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: ubuntu22

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2.0
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: app/static

  - url: /.*
    script: auto




